url: http://ercite.github.io
remote_theme: jekyll/minima@49f6dce0727a2441f0b0c265b41b5efc7b042eb6
title: ERCITE
show_excerpts: true
future: true
header_pages:
  -ChemPop.md
  -ChemMix.md
  -EcosystemProject.md
  -Events.md
  -Publications.md
  -ProjectPartners.md
repository: ercite/ercite.github.io
